---
slug: cad101
filename: cad101
title: Title of the Book
subtitle: Change me
description: Change me.
author: Author Name
copyright: 2023
uuid: 9c9e228a-b880-4af5-99ce-601e6a04bb72
pdf_preview_page_range: 1..30
epub_mobi_preview_chapter_range: 0..1
